### ISSUE TITLE
Replace deprecated "AmazonEC2RoleforSSM" policy

### ISSUE THREAD

**Issue by danielbayerlein** [pepperize/cdk-autoscaling-gitlab-runner#139]
This policy (`AmazonEC2RoleforSSM`) will soon be deprecated. Please use `AmazonSSMManagedInstanceCore` policy to enable AWS Systems Manager service core functionality on EC2 instances.

https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/f6a65130f8225e6459200c3f437f6675dcdd810c/src/runner/job-runner.ts#L89

**Comment by danielbayerlein** [comment]
If you like, I will create a PR for it.

**Comment by pflorek** [comment]
@danielbayerlein that would be a great help!

actually for the manager/coordinator it's actually fixed:

https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/7d7271bc3e169922e48ba04d27fe936ac80035fe/src/runner/manager.ts#L110
