### ISSUE TITLE
Support for GitLab 15.0

### ISSUE THREAD

**Issue by danielbayerlein** [pepperize/cdk-autoscaling-gitlab-runner#227]
GitLab is moving to 15.0 with a few breaking changes: https://about.gitlab.com/blog/2022/04/18/gitlab-releases-15-breaking-changes

The following change will probably affect the package: `Must explicitly assign AuthenticationType for [runners.cache.s3]`. The `AuthenticationType` must be `IAM` or `credentials`.

**Comment by pflorek** [comment]
Should we add it now to the runner's toml config?
