### ISSUE TITLE
KeyPair name for runner instances

### ISSUE THREAD

**Issue by marco-streng** [pepperize/cdk-autoscaling-gitlab-runner#236]
According to the [documentation](https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/main/API.md#pepperizecdkautoscalinggitlabrunnergitlabrunnerautoscalingmanagerpropertykeypairname) it is possible to specify a custom `keyPairName` which is applied to the Manager Instance and the Auto Scaling Group.

The launched Runner Instances still use new created Key Pairs. But for compliance reasons, sometimes it is only possible to use imported key pairs.

Is there a way to also set a `keyPairName` for the Runner Instances?

**Comment by pflorek** [comment]
Hey @marco-streng , yes, the `keypairName` just needs to be added to https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/19f6d60b1dab870f4c857b10a26d0170a6c17f22/src/runner-configuration/machine-options.ts#L5 

Then it will be passed by the config.toml as `amazonec2-keypair-name` to the executor's driver https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/drivers/amazonec2/amazonec2.go#L398

**Comment by pflorek** [comment]
@marco-streng to access the manager or the runners you may also use the SSM connect feature from the AWS EC2 Web Console.

**Comment by pflorek** [comment]
The difficulty using the job runners `keypairName` will be to get the private key onto the manager https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/drivers/amazonec2/amazonec2.go#L1020 It could be fetched by the cloud init script from SecretManager.
