### ISSUE TITLE
Customize runner instande (install amazon-ecr-credential-helper)

### ISSUE THREAD

**Issue by maciejmatuszak** [pepperize/cdk-autoscaling-gitlab-runner#271]
I would like to be able to access AWS ECR repository from gitlab runner. i.e. specify private AWS ECR repository as `image` for gitlab CI job. In order to do so the [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) has to be installed on runner machine.
Currently I do not see way to customise the runner machine (not the agent).
Poking around code I think it should go here https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/fe21859c2a52f53b7b344dca077dab63c15fcb36/src/runner/manager.ts#L233 as another package:
`InitPackage.yum("amazon-ecr-credential-helper"),` 
any advice how to accomplish that?

**Comment by pflorek** [comment]
Hey @maciejmatuszak ,

the easiest is to provide a [Runner's AMI](https://github.com/pepperize/cdk-autoscaling-gitlab-runner/blob/main/API.md#machineimageoptional-) with the amazon-ecr-credential-helper installed and then configure the `DOCKER_AUTH_CONFIG` environment variable.

Another option would be to implement the user data feature for the Runner's machine options https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/drivers/amazonec2/amazonec2.go#L594 and store the base64 encoded user data file on the Manager instance.
