### ISSUE TITLE
install amazon-ecr-credential-helper fails occasionally

### ISSUE THREAD

**Issue by maciejmatuszak** [pepperize/cdk-autoscaling-gitlab-runner#328]
I was using the latest release that includes ecr credential helper.
Occasionally this fail in spectacular manner. It start spinning up VM's and those fail and new is spinning up in loop. at one point deleting the VM's was not happening and I ended up with 8 quite large VM's, before it hit my resource limit. Luckily I notice it early or it would be 💰💰💰💰 :)
I spend some time investigating the issue. Turns out it fail at the `apt-get update` step.  sorry I do not have the logs handy.
I found entries in the actual runner (not the manager) logs complaining about the apt lock failed. This is know issue using ubuntu like system. When ubuntu starts the `apt-daily.service` ran very early in power up sequence. If you unlucky the `apt-get update` or `apt-get install ...` will conflict as those can not run concurrently and using file based lock.
Not sure how to solve it, there does not seems to be universal solution. Best description I found: https://saveriomiroddi.github.io/Handling-the-apt-lock-on-ubuntu-server-installations/ 

For now can we make the installation of amazon-ecr-credential-helper optional?

**Comment by pflorek** [comment]
@maciejmatuszak 

Yes, apologize for this, I just did an ugly hack on it. I believe in either Custom AMI or CloudInit for it. On my job runners the manager somehow ignores it and starts the job execution.

Sure, we may disable it. Would you like to open a PR for it?

I can't remember exactly, can we just use IAM Policies so that the Job Runner is allowed to fetch from ECR?

**Comment by anux-linux** [comment]
Have you tried to set the DPkg::Lock::Timeout? Looks like this would fix the racecondition as mentioned here: 
https://blog.sinjakli.co.uk/2021/10/25/waiting-for-apt-locks-without-the-hacky-bash-scripts/
